[package]
name = "cli-common"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
rustix.workspace = true
jiff = { workspace = true, optional = true }

[features]
local-time = ["dep:jiff"]
