mod palette;
pub(crate) use palette::Palette;

use cli_common::Language;
use ratatui::{
    layout::{Alignment, Constraint, Flex, Layout, Margin, Rect},
    style::Style,
    text::{Line, Span},
    widgets::{Paragraph, Wrap},
    Frame,
};
use std::time::Duration;

// Built in, not generated by a subprocess/font dependency. Center the whole
// block, not each line independently: leading spaces are part of the letters.
const REMAINING: [&str; 8] = [
    r"                          _       _             ",
    r"                         (_)     (_)            ",
    r"  _ __ ___ _ __ ___   __ _ _ _ __  _ _ __   __ _ ",
    r" | '__/ _ \ '_ ` _ \ / _` | | '_ \| | '_ \ / _` |",
    r" | | |  __/ | | | | | (_| | | | | | | | | | (_| |",
    r" |_|  \___|_| |_| |_|\__,_|_|_| |_|_|_| |_|\__, |",
    r"                                          __/ |",
    r"                                         |___/ ",
];
// Figlet-standard-style digits so the clock matches the banner's lettering.
// Every glyph is at most SLOT columns wide so clock cells never move when
// their digit changes; narrow glyphs (`1`, `:`) center inside their cell.
const DIGIT_ROWS: usize = 6;
const SLOT: usize = 7;
const DIGITS: [[&str; DIGIT_ROWS]; 10] = [
    [
        r"  ___  ", r" / _ \ ", r"| | | |", r"| |_| |", r" \___/ ", "       ",
    ],
    ["  _ ", " / |", " | |", " | |", " |_|", "    "],
    [
        r" ____  ", r"|___ \ ", r"  __) |", r" / __/ ", r"|_____|", "       ",
    ],
    [
        r" _____ ", r"|___ / ", r"  |_ \ ", r" ___) |", r"|____/ ", "       ",
    ],
    [
        r" _  _  ", r"| || | ", r"| ||_| ", r"   | | ", r"   |_| ", "       ",
    ],
    [
        r" ____  ", r"| ___| ", r"|___ \ ", r" ___) |", r"|____/ ", "       ",
    ],
    [
        r"  __   ", r" / /_  ", r"| '_ \ ", r"| (_) |", r" \___/ ", "       ",
    ],
    [
        r" _____ ", r"|___  |", r"   / / ", r"  / /  ", r" / /   ", r"/_/    ",
    ],
    [
        r"  ___  ", r" ( _ ) ", r" / _ \ ", r"| (_) |", r" \___/ ", "       ",
    ],
    [
        r"  ___  ", r" / _ \ ", r"| (_) |", r" \__, |", r"   /_/ ", "       ",
    ],
];
// Two one-row dots centered on the digit body (content rows 0..=4).
const COLON: [&str; DIGIT_ROWS] = ["   ", "(_)", "   ", "(_)", "   ", "   "];
fn glyph(byte: u8) -> &'static [&'static str; DIGIT_ROWS] {
    if byte == b':' {
        &COLON
    } else {
        &DIGITS[(byte - b'0') as usize]
    }
}
const MESSAGES: [(&str, &str); 12] = [
    (
        "You don't have to earn a moment of rest.",
        "你不需要先证明什么，才值得休息。",
    ),
    (
        "A pause doesn't erase the progress you've made.",
        "歇一会儿，不会抹去你已经走过的路。",
    ),
    (
        "One small step at a time. There is room to breathe.",
        "一步一步来，也给自己留一点喘息的空间。",
    ),
    (
        "You can begin again, gently.",
        "等准备好了，可以温柔地重新开始。",
    ),
    (
        "The next small step can wait until you're ready.",
        "下一小步，可以等你准备好了再走。",
    ),
    (
        "You don't need to solve everything right now.",
        "不用现在就把所有问题都解决。",
    ),
    (
        "You've handled harder days than this one.",
        "比这更难的日子，你都走过来了。",
    ),
    (
        "Rest well now; you'll come back stronger.",
        "好好休息，回来时你会更有力量。",
    ),
    (
        "Every pause quietly recharges what's next.",
        "每一次停歇，都在悄悄为下一步充电。",
    ),
    (
        "You're doing better than you think.",
        "你做得比自己想象的更好。",
    ),
    (
        "Breathe, reset, then take the next brave step.",
        "深呼吸，缓一缓，再迈出勇敢的一步。",
    ),
    (
        "This break is part of the climb, not a pause from it.",
        "这段休息也是攀登的一部分，而不是中断。",
    ),
];

fn message(elapsed: Duration, language: Language) -> &'static str {
    let (en, zh) = MESSAGES[(elapsed.as_secs() / 8 % MESSAGES.len() as u64) as usize];
    language.text(en, zh)
}
fn time_text(seconds: u64) -> String {
    if seconds >= 3600 {
        format!(
            "{:02}:{:02}:{:02}",
            seconds / 3600,
            seconds / 60 % 60,
            seconds % 60
        )
    } else {
        format!("{:02}:{:02}", seconds / 60, seconds % 60)
    }
}
fn width(lines: &[impl AsRef<str>]) -> u16 {
    // Only bounded ASCII artwork is passed here, not localized text.
    lines.iter().map(|s| s.as_ref().len()).max().unwrap_or(0) as u16
}
// Square upsampling of one glyph. Duplicating '/' or '\\' would thicken the
// stroke into a distorted `//` staircase, so slants are redrawn as a true 45°
// stair line: one character per output row inside their s-by-s cell instead.
fn scale_glyph(lines: &[&str], s: u16) -> Vec<String> {
    let s = usize::from(s).max(1);
    // Center narrow glyphs (`1`, `:`) inside the fixed SLOT-wide cell instead
    // of leaving them flush-left under a blanket of trailing padding.
    let visible = lines
        .iter()
        .map(|line| line.trim_end().len())
        .max()
        .unwrap_or(0)
        .min(SLOT);
    let xoff = (SLOT - visible) / 2 * s;
    let mut out = vec![vec![' '; SLOT * s]; lines.len() * s];
    for (row, line) in lines.iter().enumerate() {
        for (col, byte) in line.bytes().enumerate() {
            let (y, x) = (row * s, xoff + col * s);
            match byte {
                b'/' => (0..s).for_each(|k| out[y + s - 1 - k][x + k] = '/'),
                b'\\' => (0..s).for_each(|k| out[y + k][x + k] = '\\'),
                b' ' => {}
                _ => {
                    for dy in 0..s {
                        for dx in 0..s {
                            out[y + dy][x + dx] = byte as char;
                        }
                    }
                }
            }
        }
    }
    out.into_iter()
        .map(|row| row.into_iter().collect())
        .collect()
}
fn art(frame: &mut Frame, lines: Vec<Line<'static>>, area: Rect) {
    let w = (lines.iter().map(Line::width).max().unwrap_or(0) as u16).min(area.width);
    let h = (lines.len() as u16).min(area.height);
    let rect = Rect::new(
        area.x + (area.width - w) / 2,
        area.y + (area.height - h) / 2,
        w,
        h,
    );
    frame.render_widget(Paragraph::new(lines), rect);
}
// Fixed equal-width cells: every character occupies SLOT*s columns plus one
// s-wide gap, and the strip centers as a whole, so a changing digit or colon
// never moves its neighbors. Glyphs scale squarely to keep 45° slants intact.
fn clock_art(frame: &mut Frame, area: Rect, time: &str, s: u16, style: Style) {
    let slots = vec![Constraint::Length(SLOT as u16 * s); time.len()];
    let cells = Layout::horizontal(slots)
        .spacing(s)
        .flex(Flex::Center)
        .split(area);
    for (byte, cell) in time.bytes().zip(cells.iter()) {
        art(
            frame,
            scale_glyph(glyph(byte), s)
                .into_iter()
                .map(|line| Line::styled(line, style))
                .collect(),
            *cell,
        );
    }
}
fn garden(w: u16, h: u16, stage: usize, elapsed: Duration, palette: Palette) -> Vec<Line<'static>> {
    let (w, h) = (usize::from(w), usize::from(h));
    if w == 0 || h == 0 {
        return vec![];
    }
    let mut canvas = vec![vec![(' ', Style::default()); w]; h];
    let mut put = |x: usize, y: usize, text: &str, style: Style| {
        if let Some(row) = canvas.get_mut(y) {
            for (cell, c) in row.iter_mut().skip(x).zip(text.chars()) {
                *cell = (c, style);
            }
        }
    };
    let sky = if h >= 12 && w >= 24 {
        let sun = if (elapsed.as_millis() / 500).is_multiple_of(2) {
            [r" \  |  / ", r"  .---.  ", r"-(     )-", r"  '---'  "]
        } else {
            [r"  \ | /  ", r"  .---.  ", r" (     ) ", r"--'---'--"]
        };
        for (y, row) in sun.iter().enumerate() {
            put(w * 3 / 4 - 4, y, row, palette.sun);
        }
        4
    } else {
        0
    };
    let ground = h - 1;
    put(0, ground, &"_".repeat(w), palette.ground);
    let count = (w / 14).clamp(1, 9);
    for n in 0..count {
        let x = (n + 1) * w / (count + 1);
        if stage == 0 {
            put(x, ground.saturating_sub(1), ".", palette.grass);
            continue;
        }
        let max_stem = ground.saturating_sub(sky + 1).clamp(1, 16);
        let stem = (max_stem * stage / 3).max(1).min(ground);
        let top = ground - stem;
        for y in top..ground {
            put(x, y, "|", palette.grass);
        }
        if stage >= 2 && w >= 7 && stem >= 2 {
            let leaf = ground - (stem / 2).max(1);
            put(x.saturating_sub(2), leaf, r"\ | /", palette.grass);
        }
        if stage == 3 && w >= 7 && stem >= 3 {
            put(x.saturating_sub(2), top, "(_*_)", palette.flower);
            put(x, top, "*", palette.center);
        }
    }
    // Group adjacent cells by style, avoiding a separate allocation per character.
    canvas
        .into_iter()
        .map(|row| {
            let mut spans = Vec::new();
            let mut text = String::new();
            let mut style = Style::default();
            for (c, next) in row {
                if next != style && !text.is_empty() {
                    spans.push(Span::styled(std::mem::take(&mut text), style));
                }
                style = next;
                text.push(c);
            }
            if !text.is_empty() {
                spans.push(Span::styled(text, style));
            }
            Line::from(spans)
        })
        .collect()
}

pub fn draw(
    frame: &mut Frame,
    elapsed: Duration,
    wait: Duration,
    noticed: bool,
    language: Language,
    palette: Palette,
) {
    let left = wait.saturating_sub(elapsed);
    let seconds = left.as_secs() + u64::from(left.subsec_nanos() != 0);
    let time = time_text(seconds);
    let remaining = format!("{} {time}", language.text("Remaining", "剩余"));
    let area = frame.area();
    if area.width < 24 || area.height < 10 {
        frame.render_widget(Paragraph::new(format!("afk\n{remaining}\nCtrl+C")), area);
        return;
    }
    let inner = area.inner(Margin::new(2, 1));
    let [main, comfort, notice, controls] = Layout::vertical([
        Constraint::Min(0),
        Constraint::Length(3),
        Constraint::Length(1),
        Constraint::Length(1),
    ])
    .areas(inner);
    // The slant banner font has floating i-dots and a g-descender that detach
    // when integer-scaled, so the banner always renders at its native size;
    // the spare room goes to the big clock instead.
    let large = main.width >= width(&REMAINING) && main.height >= 16;
    let title_h = if large { 8 } else { 1 };
    let gap = u16::from(main.height >= 8);
    let caption_h = 1; // Always retain a readable localized caption.
    let rows = DIGIT_ROWS as u16;
    // Remaining height hosts the scaled clock; the garden gets the leftovers.
    // A square scale keeps slanted strokes at 45° instead of fattening them.
    let budget = main.height.saturating_sub(title_h + gap + caption_h);
    let cells = time.len() as u16;
    let fit = (budget / rows).min(main.width / ((SLOT as u16 + 1) * cells - 1));
    let big_clock = fit >= 1;
    let clock_h = rows * fit.min(4);
    let [title, _, clock, caption, field] = Layout::vertical([
        Constraint::Length(title_h),
        Constraint::Length(gap),
        Constraint::Length(clock_h),
        Constraint::Length(caption_h),
        Constraint::Min(0),
    ])
    .areas(main);
    if large {
        art(
            frame,
            REMAINING
                .map(|line| Line::styled(line, palette.title))
                .to_vec(),
            title,
        );
    } else {
        let caption = if title.width >= 34 {
            language.text("afk - a small patch of grass", "afk - 一小片草地")
        } else {
            language.text("afk - take a breath", "afk - 歇一会儿")
        };
        frame.render_widget(
            Paragraph::new(caption)
                .style(palette.title)
                .alignment(Alignment::Center),
            title,
        );
    }
    if big_clock {
        clock_art(frame, clock, &time, fit.min(4), palette.clock);
    }
    frame.render_widget(
        Paragraph::new(remaining)
            .style(palette.clock)
            .alignment(Alignment::Center),
        caption,
    );
    let stage = (elapsed.as_nanos().saturating_mul(4) / wait.as_nanos().max(1)).min(3) as usize;
    art(
        frame,
        garden(field.width, field.height, stage, elapsed, palette),
        field,
    );
    frame.render_widget(
        Paragraph::new(message(elapsed, language))
            .alignment(Alignment::Center)
            .wrap(Wrap { trim: true }),
        comfort,
    );
    frame.render_widget(
        Paragraph::new(if noticed {
            language.text("the grass noticed.", "小草注意到了。")
        } else {
            ""
        })
        .alignment(Alignment::Center),
        notice,
    );
    let hint = if controls.width >= 40 {
        language.text(
            "Ctrl+C cancel | Ctrl+Z suspend",
            "Ctrl+C 取消 | Ctrl+Z 挂起",
        )
    } else {
        "Ctrl+C / Ctrl+Z"
    };
    frame.render_widget(Paragraph::new(hint).alignment(Alignment::Center), controls);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::{backend::TestBackend, buffer::Buffer, Terminal};
    fn render(w: u16, h: u16, seconds: u64, noticed: bool, language: Language) -> Buffer {
        render_with_palette(w, h, seconds, noticed, language, Palette::new(true))
    }
    fn render_with_palette(
        w: u16,
        h: u16,
        seconds: u64,
        noticed: bool,
        language: Language,
        palette: Palette,
    ) -> Buffer {
        let mut terminal = Terminal::new(TestBackend::new(w, h)).unwrap();
        terminal
            .draw(|frame| {
                draw(
                    frame,
                    Duration::from_secs(seconds),
                    Duration::from_secs(100),
                    noticed,
                    language,
                    palette,
                )
            })
            .unwrap();
        terminal.backend().buffer().clone()
    }
    fn text(buffer: &Buffer) -> String {
        buffer.content.iter().map(|cell| cell.symbol()).collect()
    }
    #[test]
    fn artwork_uses_distinct_colors_without_setting_a_background() {
        use ratatui::style::Color;
        let buffer = render(120, 70, 80, false, Language::English);
        for color in [
            Color::Cyan,
            Color::LightCyan,
            Color::Green,
            Color::Yellow,
            Color::LightMagenta,
            Color::LightYellow,
        ] {
            assert!(buffer
                .content
                .iter()
                .any(|cell| cell.fg == color && cell.symbol() != " "));
        }
        assert!(buffer.content.iter().all(|cell| cell.bg == Color::Reset));
        let flower = buffer
            .content
            .iter()
            .find(|cell| cell.symbol() == "*")
            .unwrap();
        assert_eq!(flower.fg, Color::LightYellow);
    }

    #[test]
    fn monochrome_preserves_every_character_and_layout() {
        use ratatui::style::Color;
        for (w, h) in [(12, 3), (24, 10), (80, 24), (120, 70)] {
            for seconds in [0, 30, 60, 80] {
                for language in [Language::English, Language::Chinese] {
                    let colored = render(w, h, seconds, true, language);
                    let plain =
                        render_with_palette(w, h, seconds, true, language, Palette::new(false));
                    assert_eq!(text(&colored), text(&plain));
                    assert!(plain
                        .content
                        .iter()
                        .all(|cell| cell.fg == Color::Reset && cell.bg == Color::Reset));
                }
            }
        }
    }

    #[test]
    fn grows_by_elapsed_time_without_key_penalties() {
        let start = text(&render(100, 40, 0, false, Language::English));
        let grown = text(&render(100, 40, 80, false, Language::English));
        let noticed = text(&render(100, 40, 80, true, Language::English));
        assert!(start.contains("Remaining 01:40"));
        assert!(!start.contains("(_*_)"));
        assert!(grown.contains("(_*_)") && grown.contains("Remaining 00:20"));
        assert!(noticed.contains("the grass noticed.") && noticed.contains("Remaining 00:20"));
        assert!(!grown.contains("the grass noticed."));
    }
    #[test]
    fn tiny_empty_and_chinese_frames_are_safe() {
        assert!(text(&render(12, 3, 99, true, Language::English)).contains("afk"));
        assert_eq!(text(&render(0, 0, 0, true, Language::English)), "");
        assert!(text(&render(60, 18, 80, true, Language::Chinese)).contains("小 草 注 意 到 了 。"));
    }
    #[test]
    fn banner_alignment_and_large_clock_use_the_screen() {
        let b = render(80, 24, 0, false, Language::English);
        let x = 2 + (76 - width(&REMAINING)) / 2;
        for (y, row) in REMAINING.iter().enumerate() {
            for (col, c) in row.chars().enumerate() {
                assert_eq!(b[(x + col as u16, 1 + y as u16)].symbol(), c.to_string());
            }
        }
        let large = render(160, 50, 0, false, Language::English);
        assert!(text(&large).contains("||||"));
        assert!(text(&large).contains("Remaining 01:40"));
        // Footer is anchored near the bottom, not packed into the first ten rows.
        let bottom: String = (0..160).map(|x| large[(x, 48)].symbol()).collect();
        assert!(bottom.contains("Ctrl+C cancel"));
    }
    #[test]
    fn supportive_messages_rotate_without_changing_the_clock() {
        assert_eq!(
            message(Duration::from_secs(0), Language::English),
            message(Duration::from_secs(7), Language::English)
        );
        assert_ne!(
            message(Duration::from_secs(7), Language::English),
            message(Duration::from_secs(8), Language::English)
        );
        assert_eq!(
            message(Duration::from_secs(96), Language::English),
            message(Duration::ZERO, Language::English)
        );
        let en = text(&render(80, 24, 8, false, Language::English));
        assert!(en.contains("A pause doesn't erase the progress you've made."));
        let zh = text(&render(80, 24, 0, false, Language::Chinese));
        assert!(zh.contains("你 不 需 要 先 证 明 什 么"));
    }
    #[test]
    fn motivational_messages_join_the_rotation() {
        assert_eq!(
            message(Duration::from_secs(56), Language::English),
            "Rest well now; you'll come back stronger."
        );
        assert_eq!(
            message(Duration::from_secs(88), Language::Chinese),
            "这段休息也是攀登的一部分，而不是中断。"
        );
    }
    #[test]
    fn layouts_and_clock_bounds_fit_without_panics() {
        for w in [0, 1, 12, 24, 40, 52, 60, 80, 120, 240] {
            for h in [0, 1, 3, 10, 16, 24, 30, 50, 100] {
                for language in [Language::English, Language::Chinese] {
                    render(w, h, 80, true, language);
                }
            }
        }
        assert_eq!(time_text(0), "00:00");
        assert_eq!(time_text(59), "00:59");
        assert_eq!(time_text(3600), "01:00:00");
        assert_eq!(time_text(86400), "24:00:00");
    }
    #[test]
    fn clock_glyphs_share_one_slot_width() {
        assert!(DIGITS.iter().flatten().all(|row| row.len() <= SLOT));
        assert!(DIGITS.iter().flatten().any(|row| row.len() == SLOT));
        assert!(COLON.iter().all(|row| row.len() == 3));
        assert_eq!(glyph(b':'), &COLON);
        assert_eq!(glyph(b'4'), &DIGITS[4]);
    }
    #[test]
    fn scaled_glyphs_keep_lean_45_degree_slants() {
        // Naive duplication produced `//` and `\\` pairs that broke the font.
        for digit in &DIGITS {
            let lines = scale_glyph(digit, 3);
            assert_eq!(lines.len(), DIGIT_ROWS * 3);
            for line in &lines {
                assert_eq!(line.len(), SLOT * 3);
                assert!(!line.contains("//") && !line.contains("\\\\"));
            }
        }
        // Narrow glyphs center inside their slot instead of hugging its left.
        let colon = scale_glyph(&COLON, 2);
        assert_eq!(colon[2].find('('), Some((SLOT - 3) / 2 * 2));
        let one = scale_glyph(&DIGITS[1], 2);
        assert!(one.iter().all(|line| line.starts_with(' ')));
    }
    #[test]
    fn seven_stroke_descends_continuously() {
        // Each '/' continues from one column to the upper right in the row
        // above; a column that stops descending shows a broken diagonal.
        let cols: Vec<Vec<usize>> = DIGITS[7]
            .iter()
            .map(|row| row.match_indices('/').map(|(i, _)| i).collect())
            .collect();
        for r in 3..DIGIT_ROWS {
            for c in &cols[r] {
                assert!(cols[r - 1].contains(&(c + 1)), "digit 7 gap at row {r}");
            }
        }
    }
    #[test]
    fn changing_digits_never_move_the_colon() {
        // The banner also contains parentheses, so scan only the clock rows.
        let colon_column = |elapsed: u64| -> Option<u16> {
            let b = render(80, 24, elapsed, false, Language::English);
            (9..16)
                .flat_map(|y| (0..78).map(move |x| (x, y)))
                .filter(|&(x, y)| {
                    b[(x, y)].symbol() == "("
                        && ["_", "("].contains(&b[(x + 1, y)].symbol())
                        && [")", "_"].contains(&b[(x + 2, y)].symbol())
                })
                .map(|(x, _)| x)
                .min()
        };
        // 01:31 vs 00:11: digit widths differ (1 is narrow) yet cells stay put.
        assert!(colon_column(9).is_some());
        assert_eq!(colon_column(9), colon_column(89));
        assert_eq!(colon_column(9), colon_column(49)); // 00:51
    }
}
