mod clock;
mod layout;
mod palette;
pub(crate) use palette::{ColorMode, Palette};

use cli_common::Language;
use ratatui::{
    layout::{Alignment, Rect},
    style::Style,
    text::{Line, Span},
    widgets::{Paragraph, Wrap},
    Frame,
};
use std::time::Duration;

// Built in, not generated by a subprocess/font dependency. Center the whole
// block, not each line independently: leading spaces are part of the letters.
const REMAINING: [&str; 8] = [
    r"                          _       _             ",
    r"                         (_)     (_)            ",
    r"  _ __ ___ _ __ ___   __ _ _ _ __  _ _ __   __ _ ",
    r" | '__/ _ \ '_ ` _ \ / _` | | '_ \| | '_ \ / _` |",
    r" | | |  __/ | | | | | (_| | | | | | | | | | (_| |",
    r" |_|  \___|_| |_| |_|\__,_|_|_| |_|_|_| |_|\__, |",
    r"                                            __/ |",
    r"                                           |___/ ",
];
const MESSAGES: [(&str, &str); 12] = [
    (
        "You don't have to earn a moment of rest.",
        "你不需要先证明什么，才值得休息。",
    ),
    (
        "A pause doesn't erase the progress you've made.",
        "歇一会儿，不会抹去你已经走过的路。",
    ),
    (
        "One small step at a time. There is room to breathe.",
        "一步一步来，也给自己留一点喘息的空间。",
    ),
    (
        "You can begin again, gently.",
        "等准备好了，可以温柔地重新开始。",
    ),
    (
        "The next small step can wait until you're ready.",
        "下一小步，可以等你准备好了再走。",
    ),
    (
        "You don't need to solve everything right now.",
        "不用现在就把所有问题都解决。",
    ),
    (
        "You've handled harder days than this one.",
        "比这更难的日子，你都走过来了。",
    ),
    (
        "Rest well now; you'll come back stronger.",
        "好好休息，回来时你会更有力量。",
    ),
    (
        "Every pause quietly recharges what's next.",
        "每一次停歇，都在悄悄为下一步充电。",
    ),
    (
        "You're doing better than you think.",
        "你做得比自己想象的更好。",
    ),
    (
        "Breathe, reset, then take the next brave step.",
        "深呼吸，缓一缓，再迈出勇敢的一步。",
    ),
    (
        "This break is part of the climb, not a pause from it.",
        "这段休息也是攀登的一部分，而不是中断。",
    ),
];

fn message(elapsed: Duration, language: Language) -> &'static str {
    let (en, zh) = MESSAGES[(elapsed.as_secs() / 8 % MESSAGES.len() as u64) as usize];
    language.text(en, zh)
}
fn width(lines: &[impl AsRef<str>]) -> u16 {
    // Only bounded ASCII artwork is passed here, not localized text.
    lines.iter().map(|s| s.as_ref().len()).max().unwrap_or(0) as u16
}
fn art(frame: &mut Frame, lines: Vec<Line<'static>>, area: Rect) {
    let w = (lines.iter().map(Line::width).max().unwrap_or(0) as u16).min(area.width);
    let h = (lines.len() as u16).min(area.height);
    let rect = Rect::new(
        area.x + (area.width - w) / 2,
        area.y + (area.height - h) / 2,
        w,
        h,
    );
    frame.render_widget(Paragraph::new(lines), rect);
}
fn garden(w: u16, h: u16, stage: usize, elapsed: Duration, palette: Palette) -> Vec<Line<'static>> {
    let (w, h) = (usize::from(w), usize::from(h));
    if w == 0 || h == 0 {
        return vec![];
    }
    let mut canvas = vec![vec![(' ', Style::default()); w]; h];
    let mut put = |x: usize, y: usize, text: &str, style: Style| {
        if let Some(row) = canvas.get_mut(y) {
            for (cell, c) in row.iter_mut().skip(x).zip(text.chars()) {
                *cell = (c, style);
            }
        }
    };
    let sky = if h >= 12 && w >= 24 {
        let sun = if (elapsed.as_millis() / 500).is_multiple_of(2) {
            [r" \  |  / ", r"  .---.  ", r"-(     )-", r"  '---'  "]
        } else {
            [r"  \ | /  ", r"  .---.  ", r" (     ) ", r"--'---'--"]
        };
        for (y, row) in sun.iter().enumerate() {
            put(w * 3 / 4 - 4, y, row, palette.sun);
        }
        4
    } else {
        0
    };
    let ground = h - 1;
    put(0, ground, &"_".repeat(w), palette.ground);
    let count = (w / 14).clamp(1, 9);
    for n in 0..count {
        let x = (n + 1) * w / (count + 1);
        if stage == 0 {
            put(x, ground.saturating_sub(1), ".", palette.grass);
            continue;
        }
        let max_stem = ground.saturating_sub(sky + 1).clamp(1, 16);
        let stem = (max_stem * stage / 3).max(1).min(ground);
        let top = ground - stem;
        for y in top..ground {
            put(x, y, "|", palette.grass);
        }
        if stage >= 2 && w >= 7 && stem >= 2 {
            let leaf = ground - (stem / 2).max(1);
            put(x.saturating_sub(2), leaf, r"\ | /", palette.grass);
        }
        if stage == 3 && w >= 7 && stem >= 3 {
            put(x.saturating_sub(2), top, "(_*_)", palette.flower);
            put(x, top, "*", palette.center);
        }
    }
    // Group adjacent cells by style, avoiding a separate allocation per character.
    canvas
        .into_iter()
        .map(|row| {
            let mut spans = Vec::new();
            let mut text = String::new();
            let mut style = Style::default();
            for (c, next) in row {
                if next != style && !text.is_empty() {
                    spans.push(Span::styled(std::mem::take(&mut text), style));
                }
                style = next;
                text.push(c);
            }
            if !text.is_empty() {
                spans.push(Span::styled(text, style));
            }
            Line::from(spans)
        })
        .collect()
}

pub fn draw(
    frame: &mut Frame,
    elapsed: Duration,
    wait: Duration,
    noticed: bool,
    language: Language,
    palette: Palette,
) {
    let time = clock::remaining(elapsed, wait);
    let remaining = format!("{} {time}", language.text("Remaining", "剩余"));
    let area = frame.area();
    if area.width < 24 || area.height < 10 {
        frame.render_widget(
            Paragraph::new(format!("afk\n{remaining}\nCtrl+C")).style(palette.text),
            area,
        );
        return;
    }
    let layout::SceneLayout {
        title,
        clock,
        caption,
        field,
        comfort,
        notice,
        controls,
        banner,
        scale,
    } = layout::SceneLayout::new(area, time.len(), width(&REMAINING));
    if banner {
        art(
            frame,
            REMAINING
                .map(|line| Line::styled(line, palette.title))
                .to_vec(),
            title,
        );
    } else {
        let caption = if title.width >= 34 {
            language.text("afk - a small patch of grass", "afk - 一小片草地")
        } else {
            language.text("afk - take a breath", "afk - 歇一会儿")
        };
        frame.render_widget(
            Paragraph::new(caption)
                .style(palette.title)
                .alignment(Alignment::Center),
            title,
        );
    }
    if scale != 0 {
        art(
            frame,
            clock::lines(&time, scale)
                .into_iter()
                .map(|line| Line::styled(line, palette.clock))
                .collect(),
            clock,
        );
    }
    frame.render_widget(
        Paragraph::new(remaining)
            .style(palette.clock)
            .alignment(Alignment::Center),
        caption,
    );
    let stage = (elapsed.as_nanos().saturating_mul(4) / wait.as_nanos().max(1)).min(3) as usize;
    art(
        frame,
        garden(field.width, field.height, stage, elapsed, palette),
        field,
    );
    frame.render_widget(
        Paragraph::new(message(elapsed, language))
            .style(palette.text)
            .alignment(Alignment::Center)
            .wrap(Wrap { trim: true }),
        comfort,
    );
    frame.render_widget(
        Paragraph::new(if noticed {
            language.text("the grass noticed.", "小草注意到了。")
        } else {
            ""
        })
        .style(palette.text)
        .alignment(Alignment::Center),
        notice,
    );
    let hint = if controls.width >= 40 {
        language.text(
            "Ctrl+C cancel | Ctrl+Z suspend",
            "Ctrl+C 取消 | Ctrl+Z 挂起",
        )
    } else {
        "Ctrl+C / Ctrl+Z"
    };
    frame.render_widget(
        Paragraph::new(hint)
            .style(palette.text)
            .alignment(Alignment::Center),
        controls,
    );
    palette.animate(frame.buffer_mut(), elapsed);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::{backend::TestBackend, buffer::Buffer, Terminal};
    fn render(w: u16, h: u16, seconds: u64, noticed: bool, language: Language) -> Buffer {
        render_with_palette(
            w,
            h,
            seconds,
            noticed,
            language,
            Palette::new(ColorMode::Parts, true),
        )
    }
    fn render_with_palette(
        w: u16,
        h: u16,
        seconds: u64,
        noticed: bool,
        language: Language,
        palette: Palette,
    ) -> Buffer {
        let mut terminal = Terminal::new(TestBackend::new(w, h)).unwrap();
        terminal
            .draw(|frame| {
                draw(
                    frame,
                    Duration::from_secs(seconds),
                    Duration::from_secs(100),
                    noticed,
                    language,
                    palette,
                )
            })
            .unwrap();
        terminal.backend().buffer().clone()
    }
    fn text(buffer: &Buffer) -> String {
        buffer.content.iter().map(|cell| cell.symbol()).collect()
    }
    #[test]
    fn artwork_uses_distinct_colors_without_setting_a_background() {
        use ratatui::style::Color;
        let buffer = render(120, 70, 80, false, Language::English);
        for color in [
            Color::Cyan,
            Color::LightCyan,
            Color::Green,
            Color::Yellow,
            Color::LightMagenta,
            Color::LightYellow,
        ] {
            assert!(buffer
                .content
                .iter()
                .any(|cell| cell.fg == color && cell.symbol() != " "));
        }
        assert!(buffer.content.iter().all(|cell| cell.bg == Color::Reset));
        let flower = buffer
            .content
            .iter()
            .find(|cell| cell.symbol() == "*")
            .unwrap();
        assert_eq!(flower.fg, Color::LightYellow);
    }

    #[test]
    fn monochrome_preserves_every_character_and_layout() {
        use ratatui::style::Color;
        for (w, h) in [(12, 3), (24, 10), (80, 24), (120, 70)] {
            for seconds in [0, 30, 60, 80] {
                for language in [Language::English, Language::Chinese] {
                    let colored = render(w, h, seconds, true, language);
                    let plain = render_with_palette(
                        w,
                        h,
                        seconds,
                        true,
                        language,
                        Palette::new(ColorMode::Parts, false),
                    );
                    assert_eq!(text(&colored), text(&plain));
                    assert!(plain
                        .content
                        .iter()
                        .all(|cell| cell.fg == Color::Reset && cell.bg == Color::Reset));
                }
            }
        }
    }

    #[test]
    fn color_modes_preserve_layout_and_white_covers_all_visible_text() {
        use ratatui::style::Color;
        for (w, h) in [(0, 0), (12, 3), (24, 10), (80, 24), (120, 70)] {
            for language in [Language::English, Language::Chinese] {
                let parts = render(w, h, 80, true, language);
                for mode in [ColorMode::Rainbow, ColorMode::White] {
                    let colored =
                        render_with_palette(w, h, 80, true, language, Palette::new(mode, true));
                    let plain =
                        render_with_palette(w, h, 80, true, language, Palette::new(mode, false));
                    assert_eq!(text(&parts), text(&colored));
                    assert_eq!(text(&parts), text(&plain));
                    assert!(colored.content.iter().all(|cell| cell.bg == Color::Reset));
                    assert!(plain.content.iter().all(|cell| cell.fg == Color::Reset));
                    if mode == ColorMode::White {
                        assert!(colored
                            .content
                            .iter()
                            .filter(|cell| cell.symbol() != " ")
                            .all(|cell| cell.fg == Color::White));
                    }
                }
            }
        }
    }

    #[test]
    fn rainbow_moves_across_the_banner_but_not_the_hints() {
        let palette = Palette::new(ColorMode::Rainbow, true);
        let a = render_with_palette(120, 70, 80, false, Language::English, palette);
        let b = render_with_palette(120, 70, 81, false, Language::English, palette);
        let layout = layout::SceneLayout::new(Rect::new(0, 0, 120, 70), 5, width(&REMAINING));
        assert!(layout.banner);
        let mut changed = false;
        for y in layout.title.y..layout.title.bottom() {
            for x in layout.title.x..layout.title.right() {
                assert_eq!(a[(x, y)].symbol(), b[(x, y)].symbol());
                changed |= a[(x, y)].fg != b[(x, y)].fg;
            }
        }
        assert!(changed);
        for y in layout.controls.y..layout.controls.bottom() {
            for x in layout.controls.x..layout.controls.right() {
                assert_eq!(a[(x, y)].fg, ratatui::style::Color::Reset);
            }
        }
    }

    #[test]
    fn grows_by_elapsed_time_without_key_penalties() {
        let start = text(&render(100, 40, 0, false, Language::English));
        let grown = text(&render(100, 40, 80, false, Language::English));
        let noticed = text(&render(100, 40, 80, true, Language::English));
        assert!(start.contains("Remaining 01:40"));
        assert!(!start.contains("(_*_)"));
        assert!(grown.contains("(_*_)") && grown.contains("Remaining 00:20"));
        assert!(noticed.contains("the grass noticed.") && noticed.contains("Remaining 00:20"));
        assert!(!grown.contains("the grass noticed."));
    }
    #[test]
    fn tiny_empty_and_chinese_frames_are_safe() {
        assert!(text(&render(12, 3, 99, true, Language::English)).contains("afk"));
        assert_eq!(text(&render(0, 0, 0, true, Language::English)), "");
        assert!(text(&render(60, 18, 80, true, Language::Chinese)).contains("小 草 注 意 到 了 。"));
    }
    #[test]
    fn banner_alignment_and_large_clock_use_the_screen() {
        let b = render(80, 30, 0, false, Language::English);
        let x = 2 + (76 - width(&REMAINING)) / 2;
        for (y, row) in REMAINING.iter().enumerate() {
            for (col, c) in row.chars().enumerate() {
                assert_eq!(b[(x + col as u16, 1 + y as u16)].symbol(), c.to_string());
            }
        }
        let large = render(160, 50, 0, false, Language::English);
        let plan = layout::SceneLayout::new(Rect::new(0, 0, 160, 50), 5, width(&REMAINING));
        let clock = clock::lines("01:40", plan.scale);
        let x = plan.clock.x + (plan.clock.width - clock[0].len() as u16) / 2;
        for (y, row) in clock.iter().enumerate() {
            for (col, c) in row.chars().enumerate() {
                assert_eq!(
                    large[(x + col as u16, plan.clock.y + y as u16)].symbol(),
                    c.to_string()
                );
            }
        }
        assert!(text(&large).contains("Remaining 01:40"));
        // Footer is anchored near the bottom, not packed into the first ten rows.
        let bottom: String = (0..160).map(|x| large[(x, 48)].symbol()).collect();
        assert!(bottom.contains("Ctrl+C cancel"));
    }
    #[test]
    fn supportive_messages_rotate_without_changing_the_clock() {
        assert_eq!(
            message(Duration::from_secs(0), Language::English),
            message(Duration::from_secs(7), Language::English)
        );
        assert_ne!(
            message(Duration::from_secs(7), Language::English),
            message(Duration::from_secs(8), Language::English)
        );
        assert_eq!(
            message(Duration::from_secs(96), Language::English),
            message(Duration::ZERO, Language::English)
        );
        let en = text(&render(80, 24, 8, false, Language::English));
        assert!(en.contains("A pause doesn't erase the progress you've made."));
        let zh = text(&render(80, 24, 0, false, Language::Chinese));
        assert!(zh.contains("你 不 需 要 先 证 明 什 么"));
    }
    #[test]
    fn motivational_messages_join_the_rotation() {
        assert_eq!(
            message(Duration::from_secs(56), Language::English),
            "Rest well now; you'll come back stronger."
        );
        assert_eq!(
            message(Duration::from_secs(88), Language::Chinese),
            "这段休息也是攀登的一部分，而不是中断。"
        );
    }
    #[test]
    fn layouts_and_clock_bounds_fit_without_panics() {
        for w in [0, 1, 12, 24, 40, 52, 60, 80, 120, 240] {
            for h in [0, 1, 3, 10, 16, 24, 30, 50, 100] {
                for language in [Language::English, Language::Chinese] {
                    render(w, h, 80, true, language);
                }
            }
        }
    }
}
