#[path = "../../tests/human_support.rs"]
mod support;
use std::fs;
use std::os::unix::fs::{symlink, PermissionsExt};
use support::*;
const BIN: &str = env!("CARGO_BIN_EXE_sprinkle");
#[test]
fn cli_basics() {
    basics(BIN, "sprinkle");
}
fn fixture() -> Fixture {
    let f = Fixture::new(BIN, true);
    for i in 0..40 {
        fs::write(f.repo.join(format!("f{i}.rs")), "fn main() {}\n").unwrap();
    }
    fs::write(f.repo.join(".gitignore"), "target/\n").unwrap();
    f.git(&["add", "."]);
    f.git(&["commit", "-qm", "files"]);
    f
}
#[test]
fn isolated_reproducible_patch_and_undo() {
    let f = fixture();
    let head = f.git(&["rev-parse", "HEAD"]).stdout;
    let branch = f.git(&["symbolic-ref", "HEAD"]).stdout;
    code(&f.run(&[]), 0);
    let copy = f.copy();
    assert!(f.git(&["status", "--porcelain"]).stdout.is_empty());
    assert_eq!(f.git(&["rev-parse", "HEAD"]).stdout, head);
    assert_eq!(f.git(&["symbolic-ref", "HEAD"]).stdout, branch);
    assert_eq!(
        fs::metadata(&copy).unwrap().permissions().mode() & 0o777,
        0o700
    );
    let diff = f.run(&["diff"]);
    code(&diff, 0);
    assert!(text(&diff.stdout).contains("+//"));
    code(&f.cmd().current_dir(&copy).arg("undo").output().unwrap(), 1);
    code(&f.run(&["undo"]), 0);
    assert!(!copy.exists());
    code(&f.run(&["undo"]), 1);
    code(&f.run(&["worktree"]), 0);
    assert_eq!(f.run(&["diff"]).stdout, diff.stdout);
    code(&f.run(&["undo"]), 0);
}
#[test]
fn rejects_dirty_and_unknown_resources() {
    let f = fixture();
    fs::write(f.repo.join("unknown"), "x").unwrap();
    code(&f.run(&[]), 1);
    assert!(f.find("manifest.json").is_empty());
    fs::remove_file(f.repo.join("unknown")).unwrap();
    f.git(&["branch", "sprinkle/not-owned"]);
    code(&f.run(&["undo"]), 1);
    code(&f.run(&["diff"]), 1);
}
#[test]
fn protects_edits_ignored_staged_commits_and_locks() {
    let f = fixture();
    code(&f.run(&[]), 0);
    let copy = f.copy();
    let original = fs::read(copy.join("code.rs")).unwrap();
    fs::write(copy.join("code.rs"), "user work\n").unwrap();
    code(&f.run(&["undo"]), 1);
    assert!(copy.exists());
    let diff = f.run(&["diff"]);
    code(&diff, 0);
    assert!(!text(&diff.stdout).contains("user work"));
    assert!(text(&diff.stderr).contains("creation-time"));
    fs::write(copy.join("code.rs"), original).unwrap();
    fs::create_dir(copy.join("target")).unwrap();
    fs::write(copy.join("target/build"), "x").unwrap();
    code(&f.run(&["undo"]), 1);
    fs::remove_dir_all(copy.join("target")).unwrap();
    f.git(&["worktree", "lock", copy.to_str().unwrap()]);
    code(&f.run(&["undo"]), 1);
    f.git(&["worktree", "unlock", copy.to_str().unwrap()]);
    let mut c = std::process::Command::new("git");
    f.environment(&mut c);
    assert!(c
        .current_dir(&copy)
        .args(["add", "."])
        .status()
        .unwrap()
        .success());
    code(&f.run(&["undo"]), 1);
    let mut c = std::process::Command::new("git");
    f.environment(&mut c);
    assert!(c
        .current_dir(&copy)
        .args(["commit", "-qm", "keep it"])
        .status()
        .unwrap()
        .success());
    code(&f.run(&["undo"]), 1);
}
#[test]
fn skips_unsafe_files_and_preserves_modes() {
    let f = fixture();
    fs::write(f.repo.join("raw.rs"), "let s=r###\"open\"##;\n").unwrap();
    fs::write(
        f.repo.join("generated.go"),
        "// Code generated by test. DO NOT EDIT\npackage p\n",
    )
    .unwrap();
    fs::write(f.repo.join("unclosed.md"), "```\nhello\n").unwrap();
    symlink("/etc/passwd", f.repo.join("link.rs")).unwrap();
    fs::set_permissions(f.repo.join("f2.rs"), fs::Permissions::from_mode(0o755)).unwrap();
    f.git(&["add", "."]);
    f.git(&["commit", "-qm", "edge cases"]);
    code(&f.run(&[]), 0);
    let copy = f.copy();
    for p in ["raw.rs", "generated.go", "unclosed.md"] {
        assert_eq!(
            fs::read(copy.join(p)).unwrap(),
            fs::read(f.repo.join(p)).unwrap()
        );
    }
    assert_eq!(
        fs::read_link(copy.join("link.rs")).unwrap(),
        std::path::PathBuf::from("/etc/passwd")
    );
    assert_eq!(
        fs::metadata(copy.join("f2.rs"))
            .unwrap()
            .permissions()
            .mode()
            & 0o777,
        0o755
    );
    code(&f.run(&["undo"]), 0);
}
#[test]
fn disables_hooks_and_refuses_filters() {
    let f = fixture();
    let marker = f.root.join("hook-ran");
    let hook = f.repo.join(".git/hooks/post-checkout");
    fs::write(&hook, format!("#!/bin/sh\ntouch '{}'\n", marker.display())).unwrap();
    fs::set_permissions(hook, fs::Permissions::from_mode(0o755)).unwrap();
    code(&f.run(&[]), 0);
    assert!(!marker.exists());
    code(&f.run(&["undo"]), 0);
    f.git(&[
        "config",
        "filter.bad.smudge",
        &format!("touch '{}'", marker.display()),
    ]);
    code(&f.run(&[]), 1);
    assert!(!marker.exists());
}
#[test]
fn newest_sessions_and_tampering() {
    let f = fixture();
    code(&f.run(&[]), 0);
    let first = f.copy();
    code(&f.run(&[]), 0);
    code(&f.run(&["undo"]), 0);
    assert!(first.exists());
    let manifests = f.find("manifest.json");
    let store = f.store();
    let active = manifests
        .iter()
        .find(|p| store.read::<serde_json::Value>(p).unwrap().unwrap()["phase"] == "active")
        .unwrap();
    fs::write(active, b"broken").unwrap();
    code(&f.run(&["undo"]), 1);
    assert!(first.exists());
}
#[test]
fn zero_candidates_still_creates_managed_copy() {
    let f = Fixture::new(BIN, true);
    fs::remove_file(f.repo.join("code.rs")).unwrap();
    fs::write(f.repo.join("plain.txt"), "hi\n").unwrap();
    f.git(&["add", "-A"]);
    f.git(&["commit", "-qm", "plain"]);
    let o = f.run(&[]);
    code(&o, 0);
    assert!(text(&o.stdout).contains("Comments added: 0"));
    code(&f.run(&["undo"]), 0);
}
#[test]
fn resume_interrupted_undo_stages() {
    let f = fixture();
    code(&f.run(&[]), 0);
    let manifest = f.find("manifest.json").pop().unwrap();
    let store = f.store();
    let mut m: serde_json::Value = store.read(&manifest).unwrap().unwrap();
    m["phase"] = "restoring".into();
    store.write(&manifest, &m).unwrap();
    code(&f.run(&["undo"]), 0);
}
