#[path = "../../tests/human_support.rs"]
mod support;
use std::fs;
use std::os::unix::fs::{symlink, PermissionsExt};
use std::path::PathBuf;
use support::*;
const BIN: &str = env!("CARGO_BIN_EXE_sprinkle");
#[test]
fn cli_basics() {
    basics(BIN, "sprinkle");
    let f = Fixture::new(BIN, false);
    for locale in ["C", "zh_CN.UTF-8"] {
        let output = f
            .cmd()
            .arg("--help")
            .env("LC_ALL", locale)
            .output()
            .unwrap();
        code(&output, 0);
        assert!(!text(&output.stdout).contains("SPRINKLE_SEED"));
    }
}
fn fixture() -> Fixture {
    let mut f = Fixture::new(BIN, true);
    f.env.push(("SPRINKLE_SEED", "42"));
    for i in 0..40 {
        fs::write(f.repo.join(format!("f{i}.rs")), "fn main() {}\n").unwrap();
    }
    fs::write(f.repo.join(".gitignore"), "target/\n").unwrap();
    f.git(&["add", "."]);
    f.git(&["commit", "-qm", "files"]);
    f
}
#[test]
fn isolated_reproducible_patch_and_undo() {
    let f = fixture();
    let head = f.git(&["rev-parse", "HEAD"]).stdout;
    let branch = f.git(&["symbolic-ref", "HEAD"]).stdout;
    code(&f.run(&[]), 0);
    let copy = f.copy();
    assert!(f.git(&["status", "--porcelain"]).stdout.is_empty());
    assert_eq!(f.git(&["rev-parse", "HEAD"]).stdout, head);
    assert_eq!(f.git(&["symbolic-ref", "HEAD"]).stdout, branch);
    assert_eq!(
        fs::metadata(&copy).unwrap().permissions().mode() & 0o777,
        0o700
    );
    let diff = f.run(&["diff"]);
    code(&diff, 0);
    assert!(text(&diff.stdout).contains("+//"));
    code(&f.cmd().current_dir(&copy).arg("undo").output().unwrap(), 1);
    code(&f.run(&["undo"]), 0);
    assert!(!copy.exists());
    code(&f.run(&["undo"]), 1);
    code(&f.run(&["worktree"]), 0);
    assert_eq!(f.run(&["diff"]).stdout, diff.stdout);
    code(&f.run(&["undo"]), 0);
}
#[test]
fn rejects_dirty_and_unknown_resources() {
    let f = fixture();
    fs::write(f.repo.join("unknown"), "x").unwrap();
    code(&f.run(&[]), 1);
    assert!(f.find("manifest.json").is_empty());
    fs::remove_file(f.repo.join("unknown")).unwrap();
    f.git(&["branch", "sprinkle/not-owned"]);
    code(&f.run(&["undo"]), 1);
    code(&f.run(&["diff"]), 1);
    assert_eq!(
        f.git(&["rev-parse", "sprinkle/not-owned"]).stdout,
        f.git(&["rev-parse", "HEAD"]).stdout
    );
}
#[test]
fn protects_edits_ignored_staged_commits_and_locks() {
    let f = fixture();
    code(&f.run(&[]), 0);
    let copy = f.copy();
    let original = fs::read(copy.join("code.rs")).unwrap();
    fs::write(copy.join("code.rs"), "user work\n").unwrap();
    code(&f.run(&["undo"]), 1);
    assert!(copy.exists());
    let diff = f.run(&["diff"]);
    code(&diff, 0);
    assert!(!text(&diff.stdout).contains("user work"));
    assert!(text(&diff.stderr).contains("creation-time"));
    fs::write(copy.join("code.rs"), original).unwrap();
    fs::create_dir(copy.join("target")).unwrap();
    fs::write(copy.join("target/build"), "x").unwrap();
    code(&f.run(&["undo"]), 1);
    fs::remove_dir_all(copy.join("target")).unwrap();
    f.git(&["worktree", "lock", copy.to_str().unwrap()]);
    code(&f.run(&["undo"]), 1);
    f.git(&["worktree", "unlock", copy.to_str().unwrap()]);
    let mut c = std::process::Command::new("git");
    f.environment(&mut c);
    assert!(c
        .current_dir(&copy)
        .args(["add", "."])
        .status()
        .unwrap()
        .success());
    code(&f.run(&["undo"]), 1);
    let mut c = std::process::Command::new("git");
    f.environment(&mut c);
    assert!(c
        .current_dir(&copy)
        .args(["commit", "-qm", "keep it"])
        .status()
        .unwrap()
        .success());
    code(&f.run(&["undo"]), 1);
}
#[test]
fn skips_unsafe_files_and_preserves_modes() {
    let f = fixture();
    fs::write(f.repo.join("raw.rs"), "let s=r###\"open\"##;\n").unwrap();
    fs::write(
        f.repo.join("generated.go"),
        "// Code generated by test. DO NOT EDIT\npackage p\n",
    )
    .unwrap();
    fs::write(f.repo.join("unclosed.md"), "```\nhello\n").unwrap();
    symlink("/etc/passwd", f.repo.join("link.rs")).unwrap();
    // Make all ordinary candidates executable so at least one edited file,
    // not merely an untouched random candidate, exercises mode preservation.
    for i in 0..40 {
        fs::set_permissions(
            f.repo.join(format!("f{i}.rs")),
            fs::Permissions::from_mode(0o755),
        )
        .unwrap();
    }
    f.git(&["add", "."]);
    f.git(&["commit", "-qm", "edge cases"]);
    code(&f.run(&[]), 0);
    let copy = f.copy();
    for p in ["raw.rs", "generated.go", "unclosed.md"] {
        assert_eq!(
            fs::read(copy.join(p)).unwrap(),
            fs::read(f.repo.join(p)).unwrap()
        );
    }
    assert_eq!(
        fs::read_link(copy.join("link.rs")).unwrap(),
        std::path::PathBuf::from("/etc/passwd")
    );
    let manifest: serde_json::Value = f
        .store()
        .read(&f.find("manifest.json").pop().unwrap())
        .unwrap()
        .unwrap();
    // Unchanged unsafe files alone prove nothing: random selection may skip
    // them even if the syntax/symlink guards have been removed.
    assert_eq!(manifest["skipped"]["syntax-or-text"], 3);
    assert_eq!(manifest["skipped"]["symlink"], 1);
    let mut edited_executables = 0;
    for file in manifest["files"].as_array().unwrap() {
        let bytes: Vec<u8> = serde_json::from_value(file["path"].clone()).unwrap();
        let path = cli_common::state::path_from(&bytes);
        if file["mode"].as_u64().unwrap() & 0o777 == 0o755
            && !file["addition"].as_str().unwrap().is_empty()
        {
            edited_executables += 1;
            assert_ne!(
                fs::read(copy.join(&path)).unwrap(),
                fs::read(f.repo.join(&path)).unwrap()
            );
            assert_eq!(
                fs::metadata(copy.join(path)).unwrap().permissions().mode() & 0o777,
                0o755
            );
        }
    }
    assert!(edited_executables > 0);
    code(&f.run(&["undo"]), 0);
}
#[test]
fn disables_hooks_and_refuses_filters() {
    let f = fixture();
    let marker = f.root.join("hook-ran");
    let hook = f.repo.join(".git/hooks/post-checkout");
    fs::write(&hook, format!("#!/bin/sh\ntouch '{}'\n", marker.display())).unwrap();
    fs::set_permissions(hook, fs::Permissions::from_mode(0o755)).unwrap();
    code(&f.run(&[]), 0);
    assert!(!marker.exists());
    code(&f.run(&["undo"]), 0);
    f.git(&[
        "config",
        "filter.bad.smudge",
        &format!("touch '{}'", marker.display()),
    ]);
    code(&f.run(&[]), 1);
    assert!(!marker.exists());
}
#[test]
fn newest_sessions_and_tampering() {
    let f = fixture();
    code(&f.run(&[]), 0);
    let first = f.copy();
    code(&f.run(&[]), 0);
    code(&f.run(&["undo"]), 0);
    assert!(first.exists());
    let manifests = f.find("manifest.json");
    let store = f.store();
    let active = manifests
        .iter()
        .find(|p| store.read::<serde_json::Value>(p).unwrap().unwrap()["phase"] == "active")
        .unwrap();
    fs::write(active, b"broken").unwrap();
    code(&f.run(&["undo"]), 1);
    assert!(first.exists());
}
#[test]
fn zero_candidates_still_creates_managed_copy() {
    let f = Fixture::new(BIN, true);
    fs::remove_file(f.repo.join("code.rs")).unwrap();
    fs::write(f.repo.join("plain.txt"), "hi\n").unwrap();
    f.git(&["add", "-A"]);
    f.git(&["commit", "-qm", "plain"]);
    let o = f.run(&[]);
    code(&o, 0);
    assert!(text(&o.stdout).contains("Comments added: 0"));
    code(&f.run(&["undo"]), 0);
}
#[test]
fn resume_interrupted_undo_stages() {
    for phase in ["restoring", "removing", "removed", "deleting-ref"] {
        let f = fixture();
        code(&f.run(&[]), 0);
        let copy = f.copy();
        let manifest = f.find("manifest.json").pop().unwrap();
        let store = f.store();
        let mut m: serde_json::Value = store.read(&manifest).unwrap().unwrap();
        let modified: Vec<_> = m["files"]
            .as_array()
            .unwrap()
            .iter()
            .filter(|file| !file["addition"].as_str().unwrap().is_empty())
            .collect();
        assert!(
            modified.len() >= 2,
            "need both restored and unrestored files"
        );
        // Reconstruct real interrupted side effects, not just the phase label.
        let restored = if phase == "restoring" {
            1
        } else {
            modified.len()
        };
        for file in &modified[..restored] {
            let bytes: Vec<u8> = serde_json::from_value(file["path"].clone()).unwrap();
            let path = copy.join(cli_common::state::path_from(&bytes));
            let content = fs::read(&path).unwrap();
            let offset = file["offset"].as_u64().unwrap() as usize;
            assert_eq!(
                &content[offset..],
                file["addition"].as_str().unwrap().as_bytes()
            );
            cli_common::state::atomic(
                &path,
                &content[..offset],
                file["mode"].as_u64().unwrap() as u32 & 0o777,
            )
            .unwrap();
        }
        let branch = m["branch"].as_str().unwrap().to_owned();
        if ["removed", "deleting-ref"].contains(&phase) {
            f.git(&["worktree", "remove", copy.to_str().unwrap()]);
        }
        if phase == "deleting-ref" {
            f.git(&["update-ref", "-d", &branch, m["head"].as_str().unwrap()]);
        }
        m["phase"] = phase.into();
        store.write(&manifest, &m).unwrap();
        code(&f.run(&["undo"]), 0);
        assert!(!copy.exists(), "{phase}: copy was not removed");
        assert!(f
            .git(&["for-each-ref", "--format=%(refname)", &branch])
            .stdout
            .is_empty());
        let done: serde_json::Value = store.read(&manifest).unwrap().unwrap();
        assert_eq!(done["phase"], "done", "{phase}");
    }
}

// Managed-copy lookup belongs to sprinkle, not the shared fixture.
impl Fixture {
    pub fn copy(&self) -> PathBuf {
        fs::read_dir(&self.root)
            .unwrap()
            .flatten()
            .find(|e| {
                e.file_name()
                    .to_string_lossy()
                    .starts_with("repo-sprinkled-")
            })
            .unwrap()
            .path()
    }
}
